#!/bin/bash

# 1. Create a blank 10MB disk image
dd if=/dev/zero of=disk.img bs=1M count=10

# 2. Create Partition Table (MBR)
# 1M (2048 sectors) reserved for Bootloader+Kernel
# The rest is a Linux partition (Type 83)
echo "2048,,83,*" | sfdisk disk.img

# 3. Format the Partition
# We need to target the partition inside the image.
# We use a loopback device with an offset.
# Offset = 2048 sectors * 512 bytes = 1048576 bytes
LOOP_DEV=$(losetup -fP --show disk.img)

# Format the first partition (p1)
/sbin/mkfs.ext2 ${LOOP_DEV}p1

# 4. Mount and Copy Files
mkdir -p mnt
mount ${LOOP_DEV}p1 mnt
cp README.md mnt/
# Add other files here...
umount mnt
losetup -d $LOOP_DEV

mv disk.img build/
